spring.application.name=restaurant-backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/restaurant}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
app.seed.random-reservations.enabled=${APP_RANDOM_RESERVATIONS_ENABLED:true}
app.seed.random-reservations.days=${APP_RANDOM_RESERVATIONS_DAYS:2}
app.seed.random-reservations.min-per-day=${APP_RANDOM_RESERVATIONS_MIN_PER_DAY:3}
app.seed.random-reservations.max-per-day=${APP_RANDOM_RESERVATIONS_MAX_PER_DAY:5}
